### ISSUE TITLE
keras-tuner 1.3.5 only claims compatibility with python >=3.8

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/keras-tuner-feedstock#24]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The conda-forge packages for keras-tuner v1.3.5 show python >=3.7 as dependencies.  However, according to the keras-tuner [README](https://github.com/keras-team/keras-tuner/tree/v1.3.5), v1.3.5 of keras-tuner claims to need python >=3.8.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by Anselmoo** [comment]
@DManowitz thx for figuring it out!

If you want, you can fix it by changing 

https://github.com/conda-forge/keras-tuner-feedstock/blob/0944ab917ee9ae3213caef47ef1853e8d45bf8b3/recipe/meta.yaml#LL12C1-L22C19 

to

```yaml

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
```
